<?php
require_once __DIR__ . '/../../core/api_pairing.php';
require_once __DIR__ . '/../../core/store_kpi_finance.php';
require_once __DIR__ . '/../../core/store_accounting.php';
pairing_auth('financial.read');
$month=trim((string)($_GET['month']??date('Y-m')));[$month,$start,$end]=adena_period_bounds($month);$includeRows=(int)($_GET['include_rows']??1)===1;
$data=['month'=>$month,'system'=>adena_store_identity(),'sales_revenue'=>0.0,'purchase_total'=>0.0,'purchase_external'=>0.0,'purchase_internal'=>0.0,'expense_total'=>0.0,'payment_request_pending'=>0.0,'payment_request_paid'=>0.0,'estimated_cash_profit'=>0.0,'purchases'=>[],'expenses'=>[],'payment_requests'=>[]];
try{
  if(adena_module_table_exists('sales')){$salesMetrics=store_acc_sales_metrics($start,$end);$data['sales_revenue']=(float)$salesMetrics['net_sales'];}
  if(adena_module_table_exists('purchase_headers')){$st=db()->prepare("SELECT ph.*,s.supplier_name FROM purchase_headers ph LEFT JOIN suppliers s ON s.id=ph.supplier_id WHERE ph.purchase_date>=? AND ph.purchase_date<? AND ph.status<>'cancelled' ORDER BY ph.id DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){$amount=(float)$r['grand_total'];$internal=false;$notes=strtolower((string)($r['notes']??''));if(str_contains($notes,'dapur')||str_contains($notes,'internal transfer'))$internal=true;if(($r['status']??'')==='posted'){$data['purchase_total']+=$amount;if($internal)$data['purchase_internal']+=$amount;else$data['purchase_external']+=$amount;}if($includeRows)$data['purchases'][]=['external_id'=>(string)$r['id'],'transaction_no'=>$r['purchase_no'],'date'=>$r['purchase_date'],'supplier'=>$r['supplier_name']??'','purchase_type'=>$r['purchase_type']??'','status'=>$r['status'],'amount'=>$amount,'is_internal'=>$internal];}}
  if(adena_module_table_exists('expenses')){$st=db()->prepare("SELECT * FROM expenses WHERE expense_date>=? AND expense_date<? AND deleted_at IS NULL ORDER BY id DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){if(in_array($r['status'],['approved','paid'],true))$data['expense_total']+=(float)$r['amount'];if($includeRows)$data['expenses'][]=['external_id'=>(string)$r['id'],'record_uuid'=>$r['record_uuid'],'transaction_no'=>$r['expense_no'],'date'=>$r['expense_date'],'category'=>$r['category_name_snapshot'],'description'=>$r['title'],'status'=>$r['status'],'amount'=>(float)$r['amount'],'vendor'=>$r['vendor_name']];}}
  if(adena_module_table_exists('payment_requests')){$st=db()->prepare("SELECT * FROM payment_requests WHERE request_date>=? AND request_date<? AND deleted_at IS NULL ORDER BY id DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){if(in_array($r['status'],['draft','submitted','approved'],true))$data['payment_request_pending']+=(float)$r['amount'];if($r['status']==='paid')$data['payment_request_paid']+=(float)$r['amount'];if($includeRows)$data['payment_requests'][]=['external_id'=>(string)$r['id'],'record_uuid'=>$r['record_uuid'],'transaction_no'=>$r['request_no'],'date'=>$r['request_date'],'due_date'=>$r['due_date'],'category'=>$r['category_name_snapshot'],'description'=>$r['title'],'status'=>$r['status'],'amount'=>(float)$r['amount'],'vendor'=>$r['vendor_name']];}}
}catch(Throwable $e){pairing_err('Gagal membaca ringkasan keuangan toko: '.$e->getMessage(),500);}
try{$accounting=store_accounting_metrics($start,$end);$data['estimated_cash_profit']=(float)$accounting['operating_profit'];}catch(Throwable $e){$data['estimated_cash_profit']=$data['sales_revenue']-$data['expense_total'];}
pairing_ok(['data'=>$data]);
