<?php require_once __DIR__ . '/_boot.php';
require_once __DIR__ . '/../core/store_accounting.php';
$from = $_GET['from'] ?? date('Y-m-01'); $to = $_GET['to'] ?? date('Y-m-d');
$rows=[]; $userNames=[];
try {
  $start=$from.' 00:00:00';
  $end=date('Y-m-d 00:00:00',strtotime($to.' +1 day'));
  $metrics=store_acc_sales_metrics($start,$end,['branch_id'=>$unitId]);
  $rows=array_reverse(array_slice($metrics['details'],-300));
  $userIds=array_values(array_unique(array_filter(array_map(static fn($r)=>(int)($r['created_by']??0),$rows))));
  if($userIds){$ph=implode(',',array_fill(0,count($userIds),'?'));$st=db()->prepare("SELECT id,name FROM users WHERE id IN ($ph)");$st->execute($userIds);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $urow)$userNames[(int)$urow['id']]=(string)$urow['name'];}
} catch(Throwable $e) { $err=$e->getMessage(); } ?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Riwayat Penjualan Cabang</title><link rel="icon" href="<?php echo e(favicon_url()); ?>"><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style><?php echo $customCss; ?></style></head><body class="desktop-compact"><div class="container"><?php include __DIR__ . '/_sidebar.php'; ?><div class="main"><div class="topbar"><button class="btn" data-toggle-sidebar type="button">Menu</button><strong>Riwayat Penjualan Cabang</strong></div><div class="content"><div class="card"><form class="grid cols-4"><input type="hidden" name="unit_id" value="<?php echo e((string)$unitId); ?>"><div class="row"><label>Dari</label><input type="date" name="from" value="<?php echo e($from); ?>"></div><div class="row"><label>Sampai</label><input type="date" name="to" value="<?php echo e($to); ?>"></div><div class="row" style="align-self:end"><button class="btn" type="submit">Filter</button></div></form></div><div class="card"><table class="table"><thead><tr><th>Waktu</th><th>Jenis</th><th>No</th><th>Kasir</th><th>Metode</th><th>Bank</th><th>Qty</th><th>Kotor</th><th>Diskon</th><th>Retur</th><th>Omzet Bersih</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo e($r['event_at']); ?></td><td><?php echo e($r['event_label']); ?></td><td><?php echo e($r['transaction_code']); ?></td><td><?php echo e($userNames[(int)($r['created_by']??0)]??'-'); ?></td><td><?php echo e($r['payment_method']); ?></td><td><?php echo e($r['payment_bank']); ?></td><td><?php echo e((string)$r['qty']); ?></td><td><?php echo e(format_money($r['gross'])); ?></td><td><?php echo e(format_money($r['discount_total'])); ?></td><td><?php echo e(format_money($r['return_amount'])); ?></td><td><?php echo (float)$r['net']<0?'- ':''; ?><?php echo e(format_money(abs((float)$r['net']))); ?></td></tr><?php endforeach; if(empty($rows)): ?><tr><td colspan="11">Belum ada data.</td></tr><?php endif; ?></tbody></table></div></div></div></div><script src="<?php echo e(asset_url('assets/app.js')); ?>"></script></body></html>
