<?php
require_once __DIR__ . '/../core/db.php';
require_once __DIR__ . '/../core/functions.php';
require_once __DIR__ . '/../core/security.php';
require_once __DIR__ . '/../core/auth.php';
require_once __DIR__ . '/../core/rbac.php';
require_once __DIR__ . '/../core/api_pairing.php';
start_secure_session(); require_login(); ensure_api_pairing_schema();
$u=current_user();
if(!current_user_is_owner() && !has_menu_access($u,'settings','view')) redirect(base_url('admin/dashboard.php'));
$customCss=function_exists('setting')?setting('custom_css',''):'';
$msg=trim((string)($_GET['msg']??''));
$reopen=preg_replace('/[^a-zA-Z0-9_-]/','',(string)($_GET['reopen']??''));
$incoming=db()->query("SELECT * FROM api_pairing_requests WHERE direction='incoming' AND requester_type='backoffice' AND status IN ('pending','approved','rejected') ORDER BY FIELD(status,'pending','approved','rejected'), id DESC LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
$conns=db()->query("SELECT * FROM api_connections WHERE connection_type='backoffice' ORDER BY (status='active') DESC,id DESC LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
$pending=count(array_filter($incoming,fn($r)=>($r['status']??'')==='pending'));
$active=count(array_filter($conns,fn($r)=>($r['status']??'')==='active'));
function pairing_status_badge($s){$s=(string)$s;$c=in_array($s,['approved','active','ok'],true)?'ok':($s==='pending'?'warn':'danger');return '<span class="badge '.$c.'">'.e($s).'</span>';}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pairing Back Office</title><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style>
<?php echo $customCss; ?>
.pairing-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:14px}.pairing-head h2{margin:0 0 4px}.pairing-actions{display:flex;gap:8px;flex-wrap:wrap}.pairing-summary{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 16px}.pairing-pill{background:#fff;border:1px solid #e5e7eb;border-radius:999px;padding:7px 11px;font-size:13px}.pairing-list{display:grid;gap:10px}.pairing-row{display:grid;grid-template-columns:minmax(180px,1.3fr) minmax(180px,1fr) auto auto;align-items:center;gap:12px;border:1px solid #e5e7eb;border-radius:12px;padding:12px;background:#fff}.pairing-row small{display:block;color:#64748b;margin-top:3px}.pairing-modal{position:fixed;inset:0;background:rgba(15,23,42,.52);display:none;align-items:center;justify-content:center;padding:18px;z-index:1000}.pairing-modal.open{display:flex}.pairing-modal-box{width:min(920px,96vw);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;box-shadow:0 25px 70px rgba(15,23,42,.25)}.pairing-modal-head{position:sticky;top:0;background:#fff;display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid #e5e7eb;z-index:2}.pairing-modal-body{padding:16px}.pairing-close{border:0;background:#f1f5f9;border-radius:9px;width:36px;height:36px;cursor:pointer}.detail-grid{display:grid;grid-template-columns:170px 1fr;gap:9px 14px}.detail-grid dt{font-weight:700;color:#475569}.detail-grid dd{margin:0;overflow-wrap:anywhere}.empty-pairing{text-align:center;color:#64748b;padding:26px 12px}.compact-table{min-width:720px}.compact-table th,.compact-table td{font-size:12px;padding:8px}.inline-actions{display:flex;gap:6px;flex-wrap:wrap}.danger-link{background:#fff;border:1px solid #fecaca;color:#b91c1c}.notice{border-color:#bfdbfe!important;background:#eff6ff!important}@media(max-width:800px){.pairing-row{grid-template-columns:1fr}.pairing-head{flex-direction:column}.detail-grid{grid-template-columns:1fr}.detail-grid dt{margin-top:8px}}
</style></head><body><div class="container"><?php include __DIR__.'/partials_sidebar.php'; ?><div class="main"><div class="topbar"><button class="btn" data-toggle-sidebar type="button">Menu</button><strong>Pairing Back Office</strong></div><div class="content">
<?php if($msg!==''): ?><div class="card notice"><?php echo e($msg); ?></div><?php endif; ?>
<div class="pairing-head"><div><h2>Koneksi Back Office</h2><div class="muted">Halaman ini khusus untuk menerima dan mengelola pairing dari Back Office. Pairing antar toko, Dapur, dan pairing legacy tidak lagi dicampur di sini.</div></div><div class="pairing-actions"><button type="button" class="btn" data-open-modal="requestModal">Request <?php echo $pending?'('.$pending.')':''; ?></button><button type="button" class="btn" data-open-modal="historyModal">Riwayat</button></div></div>
<div class="pairing-summary"><span class="pairing-pill"><strong><?php echo (int)$active; ?></strong> koneksi aktif</span><span class="pairing-pill"><strong><?php echo (int)$pending; ?></strong> menunggu persetujuan</span></div>
<div class="card"><h3>Koneksi Aktif</h3><div class="pairing-list">
<?php foreach($conns as $c): if(($c['status']??'')!=='active') continue; ?>
<div class="pairing-row"><div><strong><?php echo e($c['connection_name']); ?></strong><small><?php echo e($c['remote_base_url']); ?></small></div><div><span class="muted">Scope</span><small><?php echo e($c['access_scope']); ?></small></div><div><?php echo pairing_status_badge($c['status']); ?></div><div class="inline-actions"><button type="button" class="btn btn-light" data-detail='<?php echo e(json_encode($c,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); ?>'>Detail</button><form method="post" action="<?php echo e(base_url('admin/api_pairing_action.php')); ?>" onsubmit="return confirm('Nonaktifkan koneksi Back Office ini?')"><input type="hidden" name="_csrf" value="<?php echo e(csrf_generate_token()); ?>"><input type="hidden" name="act" value="deactivate_connection"><input type="hidden" name="id" value="<?php echo (int)$c['id']; ?>"><button class="btn danger-link">Nonaktifkan</button></form></div></div>
<?php endforeach; if(!$active): ?><div class="empty-pairing">Belum ada koneksi Back Office aktif.</div><?php endif; ?>
</div></div>
<div class="pairing-modal" id="requestModal"><div class="pairing-modal-box"><div class="pairing-modal-head"><h3>Request Pairing Masuk</h3><button class="pairing-close" data-close-modal type="button">✕</button></div><div class="pairing-modal-body table-wrap"><table class="table compact-table"><thead><tr><th>Waktu</th><th>Peminta</th><th>URL</th><th>Scope</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($incoming as $r): if(($r['status']??'')!=='pending') continue; ?><tr><td><?php echo e($r['created_at']); ?></td><td><?php echo e($r['requester_name']); ?></td><td><?php echo e($r['requester_base_url']); ?></td><td><?php echo e($r['requested_scope']); ?></td><td><?php echo pairing_status_badge($r['status']); ?></td><td><div class="inline-actions"><form method="post" action="<?php echo e(base_url('admin/api_pairing_action.php')); ?>"><input type="hidden" name="_csrf" value="<?php echo e(csrf_generate_token()); ?>"><input type="hidden" name="act" value="approve"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn">Approve</button></form><form method="post" action="<?php echo e(base_url('admin/api_pairing_action.php')); ?>"><input type="hidden" name="_csrf" value="<?php echo e(csrf_generate_token()); ?>"><input type="hidden" name="act" value="reject"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn danger-link">Reject</button></form><button type="button" class="btn btn-light" data-detail='<?php echo e(json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); ?>'>Detail</button></div></td></tr><?php endforeach; if(!$pending): ?><tr><td colspan="6" class="empty-pairing">Tidak ada request yang menunggu persetujuan.</td></tr><?php endif; ?></tbody></table></div></div></div>
<div class="pairing-modal" id="historyModal"><div class="pairing-modal-box"><div class="pairing-modal-head"><h3>Riwayat Pairing Back Office</h3><button class="pairing-close" data-close-modal type="button">✕</button></div><div class="pairing-modal-body table-wrap"><table class="table compact-table"><thead><tr><th>Waktu</th><th>Peminta</th><th>URL</th><th>Status</th><th>Detail</th></tr></thead><tbody><?php foreach($incoming as $r): ?><tr><td><?php echo e($r['created_at']); ?></td><td><?php echo e($r['requester_name']); ?></td><td><?php echo e($r['requester_base_url']); ?></td><td><?php echo pairing_status_badge($r['status']); ?></td><td><button type="button" class="btn btn-light" data-detail='<?php echo e(json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); ?>'>Lihat</button></td></tr><?php endforeach; if(!$incoming): ?><tr><td colspan="5" class="empty-pairing">Belum ada riwayat pairing.</td></tr><?php endif; ?></tbody></table></div></div></div>
<div class="pairing-modal" id="detailModal"><div class="pairing-modal-box"><div class="pairing-modal-head"><h3>Detail Pairing</h3><button class="pairing-close" data-close-modal type="button">✕</button></div><div class="pairing-modal-body"><dl class="detail-grid" id="detailGrid"></dl></div></div></div>
</div></div></div><script defer src="<?php echo e(asset_url('assets/app.js')); ?>"></script><script>
(function(){function open(id){var m=document.getElementById(id);if(m)m.classList.add('open')}function close(m){if(m)m.classList.remove('open')}document.querySelectorAll('[data-open-modal]').forEach(function(b){b.addEventListener('click',function(){open(b.getAttribute('data-open-modal'))})});document.querySelectorAll('[data-close-modal]').forEach(function(b){b.addEventListener('click',function(){close(b.closest('.pairing-modal'))})});document.querySelectorAll('.pairing-modal').forEach(function(m){m.addEventListener('click',function(e){if(e.target===m)close(m)})});document.querySelectorAll('[data-detail]').forEach(function(b){b.addEventListener('click',function(){var d={};try{d=JSON.parse(b.getAttribute('data-detail')||'{}')}catch(e){}var labels={connection_name:'Nama koneksi',requester_name:'Peminta',remote_base_url:'URL remote',requester_base_url:'URL peminta',access_scope:'Scope',requested_scope:'Scope diminta',status:'Status',created_at:'Dibuat',approved_at:'Disetujui',last_test_at:'Test terakhir',last_test_status:'Status test',last_test_message:'Pesan test',last_message:'Pesan'};var html='';Object.keys(labels).forEach(function(k){if(d[k]!==undefined&&d[k]!==null&&String(d[k])!=='')html+='<dt>'+labels[k]+'</dt><dd>'+String(d[k]).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})+'</dd>'});document.getElementById('detailGrid').innerHTML=html||'<dd>Tidak ada detail.</dd>';open('detailModal')})});var reopen=<?php echo json_encode($reopen); ?>;if(reopen)open(reopen);document.addEventListener('keydown',function(e){if(e.key==='Escape')document.querySelectorAll('.pairing-modal.open').forEach(close)})})();
</script></body></html>
