<?php
require_once __DIR__ . '/../core/db.php'; require_once __DIR__ . '/../core/functions.php'; require_once __DIR__ . '/../core/security.php'; require_once __DIR__ . '/../core/auth.php'; require_once __DIR__ . '/../core/csrf.php'; require_once __DIR__ . '/../core/inventory.php';
start_secure_session(); require_admin();
ensure_rbac_schema();
$me = require_menu_access('produk', 'view'); ensure_inventory_module_schema();
$err=''; $u=current_user();
function fmt_qty_id($v, $unit=null){ return format_qty((float)$v, $unit); }
$branches=inventory_branches();
$fg = db()->query("SELECT id,name,base_unit,purchase_unit,purchase_to_base_factor,sale_unit,sale_to_base_factor FROM products WHERE product_type='finished_good' ORDER BY name ASC")->fetchAll();
$rm = db()->query("SELECT id,name,base_unit,purchase_unit,purchase_to_base_factor,sale_unit,sale_to_base_factor FROM products WHERE product_type='raw_material' ORDER BY name ASC")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){ csrf_check(); $action=(string)($_POST['action']??'save'); try {
 if($action==='save_header'){
  $id=(int)($_POST['id']??0); $branchId=(int)($_POST['branch_id']??0); $finished=(int)($_POST['finished_product_id']??0); $code=trim((string)($_POST['bom_code']??'')); $name=trim((string)($_POST['bom_name']??'')); $yield=(float)($_POST['yield_qty']??1); $isActive=isset($_POST['is_active'])?1:0;
  if($finished<=0||$code===''||$name===''||$yield<=0) throw new Exception('Data BOM header tidak valid.');
  $db=db(); $db->beginTransaction();
  if($isActive===1){ $stmt=$db->prepare("UPDATE bom_headers SET is_active=0 WHERE finished_product_id=? AND id<>?"); $stmt->execute([$finished,$id]); }
  if($id>0){ $stmt=$db->prepare("UPDATE bom_headers SET branch_id=?,finished_product_id=?,bom_code=?,bom_name=?,yield_qty=?,is_active=? WHERE id=?"); $stmt->execute([$branchId?:null,$finished,$code,$name,$yield,$isActive,$id]); }
  else { $stmt=$db->prepare("INSERT INTO bom_headers (branch_id,finished_product_id,bom_code,bom_name,yield_qty,is_active,created_by) VALUES (?,?,?,?,?,?,?)"); $stmt->execute([$branchId?:null,$finished,$code,$name,$yield,$isActive,(int)($u['id']??0)]); $id=(int)$db->lastInsertId(); }
  $db->commit(); redirect(base_url('admin/bom.php?id='.$id));
 }
 if($action==='add_item'){
  $bomId=(int)($_POST['bom_id']??0); $mat=(int)($_POST['material_product_id']??0); $qty=(float)($_POST['qty_per_yield']??0); $w=(float)($_POST['wastage_pct']??0);
  if($bomId<=0||$mat<=0||$qty<=0||$w<0) throw new Exception('Item BOM tidak valid.');
  $stmt=db()->prepare("SELECT p.product_type, bh.finished_product_id FROM products p JOIN bom_headers bh ON bh.id=? WHERE p.id=? LIMIT 1"); $stmt->execute([$bomId,$mat]); $r=$stmt->fetch();
  if(!$r||$r['product_type']!=='raw_material') throw new Exception('Material harus raw material.');
  if((int)$r['finished_product_id']===$mat) throw new Exception('Produk jadi tidak boleh jadi material dirinya sendiri.');
  $stmt=db()->prepare("SELECT id FROM bom_items WHERE bom_id=? AND material_product_id=? LIMIT 1"); $stmt->execute([$bomId,$mat]); if($stmt->fetch()) throw new Exception('Material sudah ada pada BOM ini.');
  $stmt=db()->prepare("INSERT INTO bom_items (bom_id,material_product_id,qty_per_yield,wastage_pct) VALUES (?,?,?,?)"); $stmt->execute([$bomId,$mat,$qty,$w]); redirect(base_url('admin/bom.php?id='.$bomId));
 }
 if($action==='update_item'){
  $itemId=(int)($_POST['item_id']??0); $bomId=(int)($_POST['bom_id']??0); $mat=(int)($_POST['material_product_id']??0); $qty=(float)($_POST['qty_per_yield']??0); $w=(float)($_POST['wastage_pct']??0);
  if($itemId<=0||$bomId<=0||$mat<=0||$qty<=0||$w<0) throw new Exception('Item BOM tidak valid.');
  $stmt=db()->prepare("SELECT id FROM bom_items WHERE id=? AND bom_id=? LIMIT 1"); $stmt->execute([$itemId,$bomId]); if(!$stmt->fetch()) throw new Exception('Item BOM tidak ditemukan.');
  $stmt=db()->prepare("SELECT p.product_type, bh.finished_product_id FROM products p JOIN bom_headers bh ON bh.id=? WHERE p.id=? LIMIT 1"); $stmt->execute([$bomId,$mat]); $r=$stmt->fetch();
  if(!$r||$r['product_type']!=='raw_material') throw new Exception('Material harus raw material.');
  if((int)$r['finished_product_id']===$mat) throw new Exception('Produk jadi tidak boleh jadi material dirinya sendiri.');
  $stmt=db()->prepare("SELECT id FROM bom_items WHERE bom_id=? AND material_product_id=? AND id<>? LIMIT 1"); $stmt->execute([$bomId,$mat,$itemId]); if($stmt->fetch()) throw new Exception('Material sudah ada pada BOM ini.');
  $stmt=db()->prepare("UPDATE bom_items SET material_product_id=?,qty_per_yield=?,wastage_pct=? WHERE id=? AND bom_id=?"); $stmt->execute([$mat,$qty,$w,$itemId,$bomId]); redirect(base_url('admin/bom.php?id='.$bomId));
 }
 if($action==='delete_item'){
  $itemId=(int)($_POST['item_id']??0); $bomId=(int)($_POST['bom_id']??0);
  if($itemId<=0||$bomId<=0) throw new Exception('Item BOM tidak valid.');
  $stmt=db()->prepare("DELETE FROM bom_items WHERE id=? AND bom_id=?"); $stmt->execute([$itemId,$bomId]); redirect(base_url('admin/bom.php?id='.$bomId));
 }
} catch(Throwable $e){ if(isset($db)&&$db->inTransaction()) $db->rollBack(); $err=$e->getMessage(); }}
$edit=null; $items=[]; $editItem=null;
if((int)($_GET['id']??0)>0){ $stmt=db()->prepare("SELECT * FROM bom_headers WHERE id=?"); $stmt->execute([(int)$_GET['id']]); $edit=$stmt->fetch(); if($edit){ $stmt=db()->prepare("SELECT bi.*, p.name material_name, p.base_unit, p.purchase_unit, p.purchase_to_base_factor, p.sale_unit, p.sale_to_base_factor FROM bom_items bi JOIN products p ON p.id=bi.material_product_id WHERE bi.bom_id=? ORDER BY bi.sort_order,bi.id"); $stmt->execute([(int)$edit['id']]); $items=$stmt->fetchAll(); }}
if($edit&&(int)($_GET['edit_item']??0)>0){ $stmt=db()->prepare("SELECT * FROM bom_items WHERE id=? AND bom_id=? LIMIT 1"); $stmt->execute([(int)$_GET['edit_item'],(int)$edit['id']]); $editItem=$stmt->fetch()?:null; }
$rows=db()->query("SELECT bh.*, p.name finished_name, b.branch_name FROM bom_headers bh JOIN products p ON p.id=bh.finished_product_id LEFT JOIN branches b ON b.id=bh.branch_id ORDER BY bh.id DESC")->fetchAll(); $customCss=setting('custom_css','');
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BOM Produk</title><link rel="icon" href="<?php echo e(favicon_url()); ?>"><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style><?php echo $customCss; ?></style></head><body><div class="container"><?php include __DIR__ . '/partials_sidebar.php'; ?><div class="main"><div class="topbar"><button class="btn" data-toggle-sidebar type="button">Menu</button></div><div class="content"><div class="card"><h3>BOM Produk</h3><?php if($err): ?><div class="card" style="border-color:rgba(251,113,133,.35);background:rgba(251,113,133,.10)"><?php echo e($err); ?></div><?php endif; ?><form method="post"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="save_header"><input type="hidden" name="id" value="<?php echo e((string)($edit['id']??0)); ?>"><div class="grid cols-2"><div class="row"><label>Kode BOM</label><input name="bom_code" required value="<?php echo e($edit['bom_code'] ?? 'BOM-'.date('YmdHis')); ?>"></div><div class="row"><label>Nama BOM</label><input name="bom_name" required value="<?php echo e($edit['bom_name'] ?? ''); ?>"></div></div><div class="grid cols-3"><div class="row"><label>Cabang (opsional/global)</label><select name="branch_id"><option value="0">Global</option><?php foreach($branches as $b): ?><option value="<?php echo e((string)$b['id']); ?>" <?php echo isset($edit) && (int)$edit['branch_id']===(int)$b['id']?'selected':''; ?>><?php echo e($b['branch_name']); ?></option><?php endforeach; ?></select></div><div class="row"><label>Finished Good</label><select name="finished_product_id" required><?php foreach($fg as $p): ?><option value="<?php echo e((string)$p['id']); ?>" <?php echo isset($edit) && (int)$edit['finished_product_id']===(int)$p['id']?'selected':''; ?>><?php echo e($p['name']); ?></option><?php endforeach; ?></select></div><div class="row"><label>Yield Qty</label><input type="number" min="0.0001" step="0.0001" name="yield_qty" required value="<?php echo e((string)($edit['yield_qty'] ?? '1')); ?>"></div></div><div class="row"><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" <?php echo isset($edit) ? ((int)($edit['is_active'] ?? 1)===1?'checked':'') : 'checked'; ?>> BOM aktif</label></div><button class="btn" type="submit">Simpan Header BOM</button></form>
<?php if($edit): ?><hr><h4><?php echo $editItem?'Edit Material':'Tambah Material'; ?></h4><form method="post"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="<?php echo $editItem?'update_item':'add_item'; ?>"><input type="hidden" name="bom_id" value="<?php echo e((string)$edit['id']); ?>"><?php if($editItem): ?><input type="hidden" name="item_id" value="<?php echo e((string)$editItem['id']); ?>"><?php endif; ?><div class="grid cols-3"><div class="row"><label>Material</label><select name="material_product_id"><?php foreach($rm as $m): ?><option value="<?php echo e((string)$m['id']); ?>" <?php echo $editItem&&(int)$editItem['material_product_id']===(int)$m['id']?'selected':''; ?>><?php echo e($m['name']); ?></option><?php endforeach; ?></select></div><div class="row"><label>Qty/Yield</label><input type="number" name="qty_per_yield" min="0.0001" step="0.0001" required value="<?php echo e((string)($editItem['qty_per_yield']??'')); ?>"></div><div class="row"><label>Wastage %</label><input type="number" name="wastage_pct" min="0" step="0.0001" value="<?php echo e((string)($editItem['wastage_pct']??'0')); ?>"></div></div><button class="btn" type="submit"><?php echo $editItem?'Simpan Perubahan':'Tambah Item'; ?></button><?php if($editItem): ?> <a class="btn" href="<?php echo e(base_url('admin/bom.php?id='.(int)$edit['id'])); ?>">Batal</a><?php endif; ?></form><?php endif; ?></div>
<?php if($edit): ?><div class="card"><table class="table"><thead><tr><th>Material</th><th>Qty/Yield</th><th>Wastage%</th><th>Aksi</th></tr></thead><tbody><?php foreach($items as $it): ?><tr><td><?php echo e($it['material_name']); ?></td><td><?php $um = product_unit_fallback($it); echo e(fmt_qty_id($it['qty_per_yield'], $um['base_unit'])); ?></td><td><?php echo e(format_number_custom((float)$it['wastage_pct'], 2)); ?></td><td><a class="btn" href="<?php echo e(base_url('admin/bom.php?id='.(int)$edit['id'].'&edit_item='.(int)$it['id'])); ?>">Edit</a> <form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="delete_item"><input type="hidden" name="bom_id" value="<?php echo e((string)$edit['id']); ?>"><input type="hidden" name="item_id" value="<?php echo e((string)$it['id']); ?>"><button class="btn" type="submit" onclick="return confirm('Hapus item BOM ini?')">Hapus</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<div class="card"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Produk</th><th>Cabang</th><th>Yield</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo e($r['bom_code']); ?></td><td><?php echo e($r['bom_name']); ?></td><td><?php echo e($r['finished_name']); ?></td><td><?php echo e($r['branch_name'] ?: 'Global'); ?></td><td><?php echo e(format_qty((float)$r['yield_qty'])); ?></td><td><?php echo (int)$r['is_active']===1?'Aktif':'Nonaktif'; ?></td><td><a class="btn" href="<?php echo e(base_url('admin/bom.php?id='.(int)$r['id'])); ?>">Detail</a></td></tr><?php endforeach; ?></tbody></table></div>
</div></div></div></div><script defer src="<?php echo e(asset_url('assets/app.js')); ?>"></script></body></html>
