<?php
require_once __DIR__ . '/../core/db.php';
require_once __DIR__ . '/../core/functions.php';
require_once __DIR__ . '/../core/security.php';
require_once __DIR__ . '/../core/auth.php';
require_once __DIR__ . '/../core/csrf.php';
require_once __DIR__ . '/../core/rbac.php';
require_once __DIR__ . '/../core/store_kpi_finance.php';

start_secure_session();
require_admin();
ensure_rbac_schema();
$me=adena_owner_admin_guard();
csrf_token();
$schemaReady=adena_module_table_exists('expense_categories') && adena_module_table_exists('expenses') && adena_module_table_exists('payment_requests');
$tab=(string)($_GET['tab']??'summary');
if(!in_array($tab,['summary','expenses','payments','settings','purchases'],true)) $tab='summary';
$month=$_GET['month']??date('Y-m'); if(!preg_match('/^\d{4}-\d{2}$/',$month)) $month=date('Y-m');
[$month,$start,$end]=adena_period_bounds($month);
$err=''; $ok=''; $uid=(int)($me['id']??0);

function adena_finance_category(int $id): ?array {
  if($id<=0) return null;
  $st=db()->prepare('SELECT * FROM expense_categories WHERE id=? AND deleted_at IS NULL LIMIT 1'); $st->execute([$id]);
  return $st->fetch(PDO::FETCH_ASSOC) ?: null;
}
function adena_finance_status_label(string $s): string { return match($s){'draft'=>'Draft','submitted'=>'Diajukan','approved'=>'Disetujui','paid'=>'Dibayar','rejected'=>'Ditolak','cancelled'=>'Dibatalkan',default=>$s}; }

if($schemaReady && $_SERVER['REQUEST_METHOD']==='POST'){
  try{
    csrf_check(); $action=(string)($_POST['action']??'');
    if($action==='save_category'){
      $id=(int)($_POST['id']??0); $code=strtoupper(trim((string)($_POST['category_code']??''))); $name=trim((string)($_POST['category_name']??''));
      if($code==='') $code='CUSTOM-'.date('YmdHis'); if($name==='') throw new Exception('Nama kategori wajib diisi.');
      $data=[$code,$name,trim((string)($_POST['group_name']??'')),trim((string)($_POST['description']??'')),isset($_POST['requires_approval'])?1:0,isset($_POST['requires_evidence'])?1:0,(int)($_POST['sort_order']??0)];
      if($id>0){$data[]=$id;db()->prepare('UPDATE expense_categories SET category_code=?,category_name=?,group_name=?,description=?,requires_approval=?,requires_evidence=?,sort_order=?,updated_at=NOW() WHERE id=?')->execute($data);}else{$data=array_merge([adena_uuid_v4()],$data,[$uid]);db()->prepare('INSERT INTO expense_categories(record_uuid,category_code,category_name,group_name,description,requires_approval,requires_evidence,sort_order,is_active,created_by) VALUES(?,?,?,?,?,?,?,?,1,?)')->execute($data);}
      $ok='Jenis pengeluaran disimpan.'; $tab='settings';
    } elseif($action==='toggle_category'){
      $id=(int)($_POST['id']??0);$active=(int)($_POST['active']??0)===1?1:0;db()->prepare('UPDATE expense_categories SET is_active=?,updated_at=NOW() WHERE id=?')->execute([$active,$id]);$ok='Status kategori diperbarui.';$tab='settings';
    } elseif($action==='save_expense'){
      $category=adena_finance_category((int)($_POST['category_id']??0)); if(!$category) throw new Exception('Jenis pengeluaran wajib dipilih.');
      $amount=(float)($_POST['amount']??0);$title=trim((string)($_POST['title']??''));$status=(string)($_POST['status']??'paid');if(!in_array($status,['draft','submitted','approved','paid'],true))$status='paid';
      if($title==='') throw new Exception('Uraian singkat wajib diisi.'); if($amount<=0) throw new Exception('Nominal harus lebih dari nol.'); if($category['category_code']==='OTHER' && trim((string)($_POST['description']??''))==='') throw new Exception('Kategori Lain-lain memerlukan uraian rinci.');
      $no='EXP-'.date('Ymd-His').'-'.str_pad((string)random_int(1,999),3,'0',STR_PAD_LEFT);$now=date('Y-m-d H:i:s');
      db()->prepare('INSERT INTO expenses(record_uuid,expense_no,expense_date,category_id,category_name_snapshot,title,description,amount,vendor_name,payment_method,reference_no,evidence_reference,status,due_date,approved_by,approved_at,paid_by,paid_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([
        adena_uuid_v4(),$no,(string)($_POST['expense_date']??date('Y-m-d')),(int)$category['id'],$category['category_name'],$title,trim((string)($_POST['description']??'')),$amount,trim((string)($_POST['vendor_name']??'')),trim((string)($_POST['payment_method']??'')),trim((string)($_POST['reference_no']??'')),trim((string)($_POST['evidence_reference']??'')),$status,($_POST['due_date']??'')?:null,in_array($status,['approved','paid'],true)?$uid:null,in_array($status,['approved','paid'],true)?$now:null,$status==='paid'?$uid:null,$status==='paid'?$now:null,$uid
      ]);$id=(int)db()->lastInsertId();adena_finance_audit('expense',$id,'created',['status'=>$status,'amount'=>$amount],$uid);adena_finance_outbox('expense',(string)$id,'created',['expense_no'=>$no,'status'=>$status,'amount'=>$amount]);$ok='Pengeluaran berhasil dicatat.';$tab='expenses';
    } elseif($action==='save_payment_request'){
      $category=adena_finance_category((int)($_POST['category_id']??0)); if(!$category) throw new Exception('Jenis pengeluaran wajib dipilih.');$amount=(float)($_POST['amount']??0);$title=trim((string)($_POST['title']??''));if($title===''||$amount<=0) throw new Exception('Judul dan nominal permintaan wajib diisi.');if($category['category_code']==='OTHER' && trim((string)($_POST['description']??''))==='') throw new Exception('Kategori Lain-lain memerlukan uraian rinci.');
      $no='PAYREQ-'.date('Ymd-His').'-'.str_pad((string)random_int(1,999),3,'0',STR_PAD_LEFT);
      db()->prepare('INSERT INTO payment_requests(record_uuid,request_no,request_date,category_id,category_name_snapshot,title,description,amount,vendor_name,due_date,reference_no,evidence_reference,status,requested_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,\'submitted\',?)')->execute([adena_uuid_v4(),$no,(string)($_POST['request_date']??date('Y-m-d')),(int)$category['id'],$category['category_name'],$title,trim((string)($_POST['description']??'')),$amount,trim((string)($_POST['vendor_name']??'')),($_POST['due_date']??'')?:null,trim((string)($_POST['reference_no']??'')),trim((string)($_POST['evidence_reference']??'')),$uid]);$id=(int)db()->lastInsertId();adena_finance_audit('payment_request',$id,'submitted',['amount'=>$amount],$uid);adena_finance_outbox('payment_request',(string)$id,'created',['request_no'=>$no,'status'=>'submitted','amount'=>$amount]);$ok='Permintaan pembayaran diajukan.';$tab='payments';
    } elseif($action==='payment_action'){
      $id=(int)($_POST['id']??0);$new=(string)($_POST['new_status']??'');if(!in_array($new,['approved','paid','rejected','cancelled'],true)) throw new Exception('Status tidak valid.');$st=db()->prepare('SELECT * FROM payment_requests WHERE id=? LIMIT 1 FOR UPDATE');db()->beginTransaction();$st->execute([$id]);$r=$st->fetch(PDO::FETCH_ASSOC);if(!$r)throw new Exception('Permintaan tidak ditemukan.');
      $linked=(int)($r['linked_expense_id']??0);$now=date('Y-m-d H:i:s');
      if($new==='paid' && $linked<=0){db()->prepare('INSERT INTO expenses(record_uuid,expense_no,expense_date,category_id,category_name_snapshot,title,description,amount,vendor_name,reference_no,evidence_reference,status,approved_by,approved_at,paid_by,paid_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([adena_uuid_v4(),'EXP-'.date('Ymd-His').'-'.str_pad((string)random_int(1,999),3,'0',STR_PAD_LEFT),date('Y-m-d'),$r['category_id'],$r['category_name_snapshot'],$r['title'],$r['description'],$r['amount'],$r['vendor_name'],$r['reference_no'],$r['evidence_reference'],'paid',$uid,$now,$uid,$now,$uid]);$linked=(int)db()->lastInsertId();}
      db()->prepare('UPDATE payment_requests SET status=?,approved_by=IF(? IN (\'approved\',\'paid\'),?,approved_by),approved_at=IF(? IN (\'approved\',\'paid\'),?,approved_at),paid_by=IF(?=\'paid\',?,paid_by),paid_at=IF(?=\'paid\',?,paid_at),linked_expense_id=IF(? > 0,?,linked_expense_id),rejection_reason=?,version_no=version_no+1,updated_at=NOW() WHERE id=?')->execute([$new,$new,$uid,$new,$now,$new,$uid,$new,$now,$linked,$linked,trim((string)($_POST['reason']??'')),$id]);
      adena_finance_audit('payment_request',$id,'status_'.$new,['old_status'=>$r['status'],'new_status'=>$new,'linked_expense_id'=>$linked],$uid);adena_finance_outbox('payment_request',(string)$id,'updated',['status'=>$new,'linked_expense_id'=>$linked],(int)$r['version_no']+1);$db=db();$db->commit();$ok='Status permintaan diperbarui menjadi '.adena_finance_status_label($new).'.';$tab='payments';
    }
  }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$err=$e->getMessage();}
}

$categories=$schemaReady?(db()->query('SELECT * FROM expense_categories WHERE deleted_at IS NULL ORDER BY is_active DESC,sort_order,category_name')->fetchAll(PDO::FETCH_ASSOC)?:[]):[];
$activeCategories=array_values(array_filter($categories,static fn($r)=>(int)$r['is_active']===1));
$expenses=[];$payments=[];$purchases=[];$summary=['purchases'=>0,'expenses'=>0,'pending'=>0,'paid_requests'=>0];
if($schemaReady){
  $st=db()->prepare('SELECT e.*,c.category_code,u.name created_by_name FROM expenses e LEFT JOIN expense_categories c ON c.id=e.category_id LEFT JOIN users u ON u.id=e.created_by WHERE e.expense_date>=? AND e.expense_date<? AND e.deleted_at IS NULL ORDER BY e.id DESC');$st->execute([$start,$end]);$expenses=$st->fetchAll(PDO::FETCH_ASSOC)?:[];
  $st=db()->prepare('SELECT p.*,u.name requested_by_name FROM payment_requests p LEFT JOIN users u ON u.id=p.requested_by WHERE p.request_date>=? AND p.request_date<? AND p.deleted_at IS NULL ORDER BY p.id DESC');$st->execute([$start,$end]);$payments=$st->fetchAll(PDO::FETCH_ASSOC)?:[];
  foreach($expenses as $r){if(in_array($r['status'],['approved','paid'],true))$summary['expenses']+=(float)$r['amount'];}
  foreach($payments as $r){if(in_array($r['status'],['draft','submitted','approved'],true))$summary['pending']+=(float)$r['amount'];if($r['status']==='paid')$summary['paid_requests']+=(float)$r['amount'];}
}
try{$st=db()->prepare("SELECT ph.*,s.supplier_name FROM purchase_headers ph LEFT JOIN suppliers s ON s.id=ph.supplier_id WHERE ph.purchase_date>=? AND ph.purchase_date<? AND ph.status<>'cancelled' ORDER BY ph.id DESC");$st->execute([$start,$end]);$purchases=$st->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($purchases as $r)if(($r['status']??'')==='posted')$summary['purchases']+=(float)$r['grand_total'];}catch(Throwable $e){}
$customCss=setting('custom_css','');
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Keuangan Toko</title><link rel="icon" href="<?php echo e(favicon_url()); ?>"><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style><?php echo $customCss; ?>.fin-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.fin-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.fin-metric{padding:16px;border:1px solid #e5e7eb;border-radius:12px}.fin-metric small{display:block;color:#64748b}.fin-metric b{font-size:1.35rem}</style></head><body><div class="container"><?php include __DIR__.'/partials_sidebar.php'; ?><div class="main"><div class="topbar"><button class="btn" data-toggle-sidebar type="button">Menu</button><strong>Keuangan Toko</strong></div><div class="content">
<?php if(!$schemaReady): ?><div class="alert danger">Tabel keuangan belum tersedia. Import <b>db/20260711_001_kpi_finance_sync.sql</b> melalui phpMyAdmin.</div><?php endif; ?><?php if($err): ?><div class="alert danger"><?php echo e($err); ?></div><?php endif; ?><?php if($ok): ?><div class="alert success"><?php echo e($ok); ?></div><?php endif; ?>
<div class="fin-tabs"><a class="btn <?php echo $tab==='summary'?'':'btn-light'; ?>" href="?tab=summary&month=<?php echo e($month); ?>">Ringkasan</a><a class="btn <?php echo $tab==='purchases'?'':'btn-light'; ?>" href="?tab=purchases&month=<?php echo e($month); ?>">Pembelian</a><a class="btn <?php echo $tab==='expenses'?'':'btn-light'; ?>" href="?tab=expenses&month=<?php echo e($month); ?>">Pengeluaran</a><a class="btn <?php echo $tab==='payments'?'':'btn-light'; ?>" href="?tab=payments&month=<?php echo e($month); ?>">Permintaan Pembayaran</a><a class="btn <?php echo $tab==='settings'?'':'btn-light'; ?>" href="?tab=settings">Setting Jenis</a></div>
<form method="get" style="display:flex;gap:8px;align-items:end;margin-bottom:12px"><input type="hidden" name="tab" value="<?php echo e($tab); ?>"><label>Periode<input type="month" name="month" value="<?php echo e($month); ?>"></label><button class="btn btn-light">Filter</button></form>
<?php if($tab==='summary'): ?><div class="card"><h3>Ringkasan <?php echo e($month); ?></h3><div class="fin-metrics"><div class="fin-metric"><small>Total Pembelian</small><b>Rp <?php echo number_format($summary['purchases'],0,',','.'); ?></b></div><div class="fin-metric"><small>Pengeluaran Disetujui/Dibayar</small><b>Rp <?php echo number_format($summary['expenses'],0,',','.'); ?></b></div><div class="fin-metric"><small>Permintaan Belum Selesai</small><b>Rp <?php echo number_format($summary['pending'],0,',','.'); ?></b></div><div class="fin-metric"><small>Total Arus Keluar Tercatat</small><b>Rp <?php echo number_format($summary['purchases']+$summary['expenses'],0,',','.'); ?></b></div></div><p style="color:#64748b">Pembelian adalah transaksi persediaan/barang. Pengeluaran adalah biaya nonstok. Permintaan pembayaran baru menjadi pengeluaran ketika berstatus Dibayar.</p></div>
<?php elseif($tab==='settings' && $schemaReady): ?>
<div class="card"><h3>Setting Jenis Pengeluaran</h3><?php $editCat=null;foreach($categories as $c){if((int)$c['id']===(int)($_GET['edit_category']??0))$editCat=$c;} ?><form method="post"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="save_category"><input type="hidden" name="id" value="<?php echo (int)($editCat['id']??0); ?>"><div class="grid2"><label>Kode<input name="category_code" value="<?php echo e($editCat['category_code']??''); ?>" placeholder="OTHER"></label><label>Nama Jenis<input name="category_name" value="<?php echo e($editCat['category_name']??''); ?>" required></label><label>Kelompok<input name="group_name" value="<?php echo e($editCat['group_name']??''); ?>"></label><label>Urutan<input type="number" name="sort_order" value="<?php echo e($editCat['sort_order']??0); ?>"></label></div><label>Deskripsi<textarea name="description"><?php echo e($editCat['description']??''); ?></textarea></label><label><input type="checkbox" name="requires_approval" <?php echo !empty($editCat['requires_approval'])?'checked':''; ?>> Memerlukan approval</label> <label><input type="checkbox" name="requires_evidence" <?php echo !empty($editCat['requires_evidence'])?'checked':''; ?>> Memerlukan bukti</label><br><button class="btn">Simpan</button></form></div><div class="card"><table class="table"><thead><tr><th>Kode</th><th>Jenis</th><th>Kelompok</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($categories as $c): ?><tr><td><?php echo e($c['category_code']); ?></td><td><?php echo e($c['category_name']); ?></td><td><?php echo e($c['group_name']); ?></td><td><?php echo (int)$c['is_active']===1?'Aktif':'Nonaktif'; ?></td><td><a class="btn btn-light" href="?tab=settings&edit_category=<?php echo (int)$c['id']; ?>">Edit</a> <form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="toggle_category"><input type="hidden" name="id" value="<?php echo (int)$c['id']; ?>"><input type="hidden" name="active" value="<?php echo (int)$c['is_active']===1?0:1; ?>"><button class="btn <?php echo (int)$c['is_active']===1?'btn-danger':'btn-light'; ?>"><?php echo (int)$c['is_active']===1?'Nonaktifkan':'Aktifkan'; ?></button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($tab==='expenses' && $schemaReady): ?><div class="card"><h3>Tambah Pengeluaran Nonstok</h3><form method="post"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="save_expense"><div class="grid2"><label>Tanggal<input type="date" name="expense_date" value="<?php echo e(date('Y-m-d')); ?>" required></label><label>Jenis<select name="category_id" required><option value="">- pilih -</option><?php foreach($activeCategories as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo e($c['category_name']); ?></option><?php endforeach; ?></select></label><label>Uraian Singkat<input name="title" required></label><label>Nominal<input type="number" step="0.01" min="0" name="amount" required></label><label>Vendor/Penerima<input name="vendor_name"></label><label>Metode Pembayaran<input name="payment_method" placeholder="Transfer / Tunai"></label><label>No Referensi<input name="reference_no"></label><label>Referensi Bukti<input name="evidence_reference" placeholder="Nomor invoice / nama file"></label><label>Jatuh Tempo<input type="date" name="due_date"></label><label>Status<select name="status"><option value="paid">Sudah Dibayar</option><option value="approved">Disetujui</option><option value="submitted">Diajukan</option><option value="draft">Draft</option></select></label></div><label>Uraian Rinci<textarea name="description"></textarea></label><button class="btn">Simpan Pengeluaran</button></form></div><div class="card"><h3>Daftar Pengeluaran</h3><table class="table"><thead><tr><th>No/Tanggal</th><th>Jenis</th><th>Uraian</th><th>Nominal</th><th>Status</th></tr></thead><tbody><?php foreach($expenses as $r): ?><tr><td><?php echo e($r['expense_no']); ?><br><small><?php echo e($r['expense_date']); ?></small></td><td><?php echo e($r['category_name_snapshot']); ?></td><td><b><?php echo e($r['title']); ?></b><br><small><?php echo e($r['description']); ?></small></td><td>Rp <?php echo number_format((float)$r['amount'],0,',','.'); ?></td><td><?php echo e(adena_finance_status_label($r['status'])); ?></td></tr><?php endforeach;if(!$expenses): ?><tr><td colspan="5">Belum ada pengeluaran.</td></tr><?php endif; ?></tbody></table></div>
<?php elseif($tab==='payments' && $schemaReady): ?><div class="card"><h3>Buat Permintaan Pembayaran</h3><form method="post"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="save_payment_request"><div class="grid2"><label>Tanggal<input type="date" name="request_date" value="<?php echo e(date('Y-m-d')); ?>"></label><label>Jenis<select name="category_id" required><option value="">- pilih -</option><?php foreach($activeCategories as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo e($c['category_name']); ?></option><?php endforeach; ?></select></label><label>Judul Tagihan<input name="title" required></label><label>Nominal<input type="number" step="0.01" min="0" name="amount" required></label><label>Vendor/Penerima<input name="vendor_name"></label><label>Jatuh Tempo<input type="date" name="due_date"></label><label>No Referensi<input name="reference_no"></label><label>Referensi Bukti<input name="evidence_reference"></label></div><label>Uraian<textarea name="description"></textarea></label><button class="btn">Ajukan Pembayaran</button></form></div><div class="card"><h3>Daftar Permintaan</h3><table class="table"><thead><tr><th>No</th><th>Tagihan</th><th>Nominal</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($payments as $r): ?><tr><td><?php echo e($r['request_no']); ?><br><small><?php echo e($r['request_date']); ?></small></td><td><b><?php echo e($r['title']); ?></b><br><small><?php echo e($r['category_name_snapshot'].' · '.$r['vendor_name']); ?></small></td><td>Rp <?php echo number_format((float)$r['amount'],0,',','.'); ?></td><td><?php echo e($r['due_date']?:'-'); ?></td><td><?php echo e(adena_finance_status_label($r['status'])); ?></td><td><?php if(!in_array($r['status'],['paid','rejected','cancelled'],true)): ?><form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="action" value="payment_action"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn btn-light" name="new_status" value="approved">Setujui</button> <button class="btn" name="new_status" value="paid">Tandai Dibayar</button> <button class="btn btn-danger" name="new_status" value="rejected">Tolak</button></form><?php else: ?>-<?php endif; ?></td></tr><?php endforeach;if(!$payments): ?><tr><td colspan="6">Belum ada permintaan pembayaran.</td></tr><?php endif; ?></tbody></table></div>
<?php elseif($tab==='purchases'): ?><div class="card"><h3>Rekap Pembelian</h3><p style="color:#64748b">Data berasal dari modul pembelian yang sudah ada. Pembelian internal dari dapur nantinya dieliminasi pada laporan konsolidasi Back Office.</p><table class="table"><thead><tr><th>No</th><th>Tanggal</th><th>Supplier</th><th>Jenis</th><th>Total</th><th>Status</th></tr></thead><tbody><?php foreach($purchases as $r): ?><tr><td><?php echo e($r['purchase_no']); ?></td><td><?php echo e($r['purchase_date']); ?></td><td><?php echo e($r['supplier_name']??'-'); ?></td><td><?php echo e($r['purchase_type']??'raw_material'); ?></td><td>Rp <?php echo number_format((float)$r['grand_total'],0,',','.'); ?></td><td><?php echo e($r['status']); ?></td></tr><?php endforeach;if(!$purchases): ?><tr><td colspan="6">Belum ada pembelian pada periode ini.</td></tr><?php endif; ?></tbody></table></div><?php endif; ?>
</div></div></div><script defer src="<?php echo e(asset_url('assets/app.js')); ?>"></script></body></html>
