package id.co.adena.pos.ui

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Build
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.activity.OnBackPressedCallback
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.lifecycle.lifecycleScope
import id.co.adena.pos.bluetooth.BluetoothPrinterManager
import id.co.adena.pos.bluetooth.EscPosFormatter
import id.co.adena.pos.data.PosApiPrefs
import id.co.adena.pos.data.PosLocalStore
import id.co.adena.pos.data.PrinterPrefs
import id.co.adena.pos.data.model.ReceiptItem
import id.co.adena.pos.data.model.ReceiptPayload
import id.co.adena.pos.databinding.ActivityMainBinding
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.ceil
import kotlin.math.min
import kotlin.math.roundToLong

/** Native Android mirror of adena/pos-desktop. No WebView is used. */
class MainActivity:AppCompatActivity(){
 private lateinit var b:ActivityMainBinding;private lateinit var store:PosLocalStore;private lateinit var prefs:PosApiPrefs;private lateinit var pp:PrinterPrefs;private lateinit var pm:BluetoothPrinterManager
 data class CartLine(val p:PosLocalStore.Product,var qty:Double=1.0,var discountAmount:Double=0.0,var discountType:String="fixed")
 data class PaymentLine(val method:String,val bank:String,val amount:Long,val cashReceived:Long=0,val cashChange:Long=0)
 private val cart=linkedMapOf<Long,CartLine>();private var cat:String?=null;private var search="";private var txDiscAmount=0.0;private var txDiscType="fixed";private var latestReceipt:ReceiptPayload?=null;private val paymentLines=mutableListOf<PaymentLine>()
 private val btPermission=registerForActivityResult(ActivityResultContracts.RequestPermission()){if(it)latestReceipt?.let(::printReceipt)}
 override fun onCreate(s:Bundle?){super.onCreate(s);b=ActivityMainBinding.inflate(layoutInflater);setContentView(b.root);store=PosLocalStore(this);prefs=PosApiPrefs(this);pp=PrinterPrefs(this);pm=BluetoothPrinterManager(this);if(store.productCount()==0){startActivity(Intent(this,SyncActivity::class.java));finish();return};bindTop();bindTabs();bindPos();renderAll();onBackPressedDispatcher.addCallback(this,object:OnBackPressedCallback(true){override fun handleOnBackPressed(){confirmExit()}})}
 private fun user():JSONObject=runCatching{JSONObject(prefs.userJson)}.getOrElse{JSONObject()};private fun userId()=user().optLong("id",0);private fun role()=user().optString("role","kasir").lowercase();private fun canModifyHistory()=role() in listOf("owner","admin")
 private fun bindTop(){b.brandName.text=store.setting("store_name","Adena POS");b.userLabel.text=user().optString("name",user().optString("username","Kasir"));b.btnExit.setOnClickListener{confirmExit()};b.syncButton.setOnClickListener{startActivity(Intent(this,SyncActivity::class.java))};b.btnShift.setOnClickListener{toggleShift()}}
 private fun bindTabs(){listOf(b.tabPos to b.panelPos,b.tabReceipt to b.panelReceipt,b.tabHistory to b.panelHistory,b.tabRecap to b.panelRecap,b.tabCustomers to b.panelCustomers,b.tabOrders to b.panelOrders).forEach{(btn,panel)->btn.setOnClickListener{showPanel(panel);when(panel.id){b.panelHistory.id->renderHistory("today");b.panelRecap.id->renderRecap();b.panelCustomers.id->renderCustomers();b.panelOrders.id->renderOrders();b.panelReceipt.id->renderReceipt()}}};b.historyToday.setOnClickListener{renderHistory("today")};b.historyYesterday.setOnClickListener{renderHistory("yesterday")};b.history7days.setOnClickListener{renderHistory("7days")};b.historyMonth.setOnClickListener{renderHistory("month")}}
 private fun showPanel(v:View){listOf(b.panelPos,b.panelReceipt,b.panelHistory,b.panelRecap,b.panelCustomers,b.panelOrders).forEach{it.visibility=if(it===v)View.VISIBLE else View.GONE}}
 private fun bindPos(){b.searchInput.addTextChangedListener(watcher{search=it;renderProducts()});b.txDiscountAmount.addTextChangedListener(watcher{txDiscAmount=it.toDoubleOrNull()?:0.0;renderCart()});b.txDiscountType.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("Rp","%"));b.txDiscountType.onItemSelectedListener=simpleSelected{txDiscType=if(it==1)"percent" else "fixed";renderCart()};b.cashReceived.addTextChangedListener(watcher{updateCashState()});b.payButton.setOnClickListener{if(b.multiPaymentToggle.isChecked)showMultiPaymentDialog() else paySingle()}}
 private fun renderAll(){renderCategories();renderProducts();fillGuides();fillPayments();renderCart();updateStatus();updateShift()}
 private fun renderCategories(){b.categoryContainer.removeAllViews();b.categoryContainer.addView(catButton("★  Semua Produk",null));store.getCategories().forEach{b.categoryContainer.addView(catButton(it,it))}}
 private fun catButton(label:String,value:String?)=Button(this).apply{text=label;isAllCaps=false;gravity=Gravity.START or Gravity.CENTER_VERTICAL;alpha=if(cat==value)1f else .72f;setTypeface(typeface,if(cat==value)Typeface.BOLD else Typeface.NORMAL);setOnClickListener{cat=value;renderCategories();renderProducts()}}
 private fun renderProducts(){b.productGrid.removeAllViews();store.getProducts(search,cat).forEach{p->val btn=Button(this).apply{text=(if(p.favorite)"★ " else "")+p.name+"\n"+money(p.price)+(p.currentStock?.let{"\nStok ${qtyText(it)}"}?:"");isAllCaps=false;minHeight=dp(116);background=round(Color.WHITE);setOnClickListener{add(p)}};b.productGrid.addView(btn,android.widget.GridLayout.LayoutParams().apply{width=0;height=dp(130);columnSpec=android.widget.GridLayout.spec(android.widget.GridLayout.UNDEFINED,1f);setMargins(dp(5),dp(5),dp(5),dp(5))})}}
 private fun add(p:PosLocalStore.Product){val line=cart[p.id];val n=(line?.qty?:0.0)+1;if(p.trackStock&&p.currentStock!=null&&n>p.currentStock){toast("Stok ${p.name} tidak mencukupi");return};if(line==null)cart[p.id]=CartLine(p) else line.qty=n;renderCart()}
 private fun itemGross(x:CartLine)=(x.p.price*x.qty).roundToLong();private fun disc(g:Long,a:Double,t:String):Long=if(a<=0)0 else if(t=="percent")min(g,(g*(min(100.0,a)/100)).roundToLong()) else min(g,a.roundToLong());private fun itemNet(x:CartLine)=itemGross(x)-disc(itemGross(x),x.discountAmount,x.discountType);private fun subtotal()=cart.values.sumOf(::itemNet);private fun txDiscValue()=disc(subtotal(),txDiscAmount,txDiscType);private fun total()=maxOf(0,subtotal()-txDiscValue())
 private fun renderCart(){b.cartContainer.removeAllViews();b.cartEmpty.visibility=if(cart.isEmpty())View.VISIBLE else View.GONE;cart.values.forEach{b.cartContainer.addView(cartRow(it))};b.cartItemCount.text="${qtyText(cart.values.sumOf{it.qty})} item";b.totalText.text="Total: ${money(total())}";b.payButton.isEnabled=cart.isNotEmpty();renderQuickCash();updateCashState()}
 private fun cartRow(x:CartLine):View{val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(7),dp(7),dp(7),dp(7));background=round(Color.WHITE)};root.addView(TextView(this).apply{text=x.p.name;textStyle(Typeface.BOLD);textSize=15f});val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};r.addView(Button(this).apply{text="−";setOnClickListener{change(x,-1)}});r.addView(TextView(this).apply{text=qtyText(x.qty);gravity=Gravity.CENTER;layoutParams=LinearLayout.LayoutParams(dp(44),ViewGroup.LayoutParams.WRAP_CONTENT)});r.addView(Button(this).apply{text="+";setOnClickListener{change(x,1)}});r.addView(TextView(this).apply{text=money(itemNet(x));gravity=Gravity.END;layoutParams=LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1f);setTypeface(typeface,Typeface.BOLD)});r.addView(Button(this).apply{text="Diskon";isAllCaps=false;setOnClickListener{editItemDiscount(x)}});root.addView(r);return root}
 private fun TextView.textStyle(style:Int){setTypeface(typeface,style)}
 private fun change(x:CartLine,d:Int){val n=x.qty+d;if(n<=0)cart.remove(x.p.id) else {if(x.p.trackStock&&x.p.currentStock!=null&&n>x.p.currentStock!!){toast("Stok tidak mencukupi");return};x.qty=n};renderCart()}
 private fun editItemDiscount(x:CartLine){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(18),dp(18),dp(18))};val amount=EditText(this).apply{hint="Nilai diskon";inputType=2 or 8192;setText(x.discountAmount.toString())};val type=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,listOf("Rp","%"));setSelection(if(x.discountType=="percent")1 else 0)};box.addView(amount);box.addView(type);AlertDialog.Builder(this).setTitle("Diskon ${x.p.name}").setView(box).setPositiveButton("Simpan"){_,_->x.discountAmount=amount.text.toString().toDoubleOrNull()?:0.0;x.discountType=if(type.selectedItemPosition==1)"percent" else "fixed";renderCart()}.setNegativeButton("Batal",null).show()}
 private fun fillGuides(){val gs=listOf(PosLocalStore.Guide(0,"Guide (opsional)"))+store.getGuides();b.guideSpinner.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,gs.map{it.name});b.guideSpinner.tag=gs}
 private fun fillPayments(){val ps=store.getPaymentMethods();b.paymentMethod.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,ps.map{it.name});b.paymentMethod.tag=ps;b.paymentMethod.onItemSelectedListener=simpleSelected{fillBanks();renderQuickCash();updateCashState()};fillBanks()}
 private fun fillBanks(){val p=selectedPayment();val banks=store.getBanks();b.paymentBank.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("Bank / channel")+banks.map{it.name});b.paymentBank.visibility=if(p?.requiresBank==true)View.VISIBLE else View.GONE}
 private fun selectedPayment():PosLocalStore.PaymentMethod?=(b.paymentMethod.tag as? List<*>)?.getOrNull(b.paymentMethod.selectedItemPosition) as? PosLocalStore.PaymentMethod
 private fun selectedGuide():PosLocalStore.Guide?=((b.guideSpinner.tag as? List<*>)?.getOrNull(b.guideSpinner.selectedItemPosition) as? PosLocalStore.Guide)?.takeIf{it.id>0}
 private fun isCash(code:String?)=code?.lowercase()?.let{it=="cash"||it=="tunai"||it.contains("cash")||it.contains("tunai")}==true
 private fun renderQuickCash(){b.cashQuickButtons.removeAllViews();if(!isCash(selectedPayment()?.code)){b.cashWrap.visibility=View.GONE;return};b.cashWrap.visibility=View.VISIBLE;val amounts=quickCash(total());(listOf(total())+amounts).distinct().take(5).forEach{v->b.cashQuickButtons.addView(Button(this).apply{text=if(v==total())"Uang Pas" else money(v);isAllCaps=false;setOnClickListener{b.cashReceived.setText(v.toString())}})}}
 private fun quickCash(t:Long):List<Long>{val o=linkedSetOf<Long>();listOf(1000L,5000L,10000L,20000L,50000L,100000L).forEach{s->o+=ceil(t.toDouble()/s).toLong()*s};listOf(50000L,100000L,150000L,200000L,300000L,500000L).filter{it>=t}.forEach{o+=it};return o.filter{it>=t}.sorted().take(4)}
 private fun updateCashState(){if(!isCash(selectedPayment()?.code)){b.cashChange.text="";return};val received=b.cashReceived.text.toString().toLongOrNull()?:0;b.cashChange.text="Kembalian: ${money(maxOf(0,received-total()))}"}
 private fun paySingle(){if(store.activeShift()==null){toast("Shift belum aktif. Buka shift terlebih dahulu.");return};val p=selectedPayment()?:return;val bank=if(p.requiresBank)b.paymentBank.selectedItem?.toString()?.takeIf{b.paymentBank.selectedItemPosition>0}.orEmpty() else "";if(p.requiresBank&&bank.isBlank()){toast("Bank / channel wajib dipilih");return};val cash=if(isCash(p.code))b.cashReceived.text.toString().toLongOrNull()?:0 else total();if(isCash(p.code)&&cash<total()){toast("Uang diterima kurang dari total");return};completeSale(p.code,bank,listOf(PaymentLine(p.code,bank,total(),cash,maxOf(0,cash-total()))))}
 private fun showMultiPaymentDialog(){if(store.activeShift()==null){toast("Shift belum aktif");return};paymentLines.clear();val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(16),dp(16),dp(16))};val summary=TextView(this).apply{textSize=17f};val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val add=Button(this).apply{text="Tambah Pembayaran"};box.addView(summary);box.addView(list);box.addView(add);fun render(){list.removeAllViews();paymentLines.forEachIndexed{i,p->list.addView(TextView(this).apply{text="${i+1}. ${p.method} ${p.bank} • ${money(p.amount)}"})};summary.text="Terbayar: ${money(paymentLines.sumOf{it.amount})} • Sisa: ${money(maxOf(0,total()-paymentLines.sumOf{it.amount}))}"};add.setOnClickListener{addPaymentLine{render()}};render();val dlg=AlertDialog.Builder(this).setTitle("Multi pembayaran • ${money(total())}").setView(box).setPositiveButton("Bayar",null).setNegativeButton("Batal",null).create();dlg.setOnShowListener{dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{if(paymentLines.sumOf{it.amount}!=total()){toast("Total pembayaran harus sama dengan total transaksi")}else{dlg.dismiss();completeSale("multi",paymentLines.joinToString(" + "){it.bank.ifBlank{it.method}},paymentLines)}}};dlg.show()}
 private fun addPaymentLine(done:()->Unit){val ps=store.getPaymentMethods();val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(16),dp(16),dp(16))};val sp=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,ps.map{it.name})};val bank=EditText(this).apply{hint="Bank/channel bila diperlukan"};val amount=EditText(this).apply{hint="Nominal";inputType=2;setText(maxOf(0,total()-paymentLines.sumOf{it.amount}).toString())};box.addView(sp);box.addView(bank);box.addView(amount);AlertDialog.Builder(this).setTitle("Tambah Pembayaran").setView(box).setPositiveButton("Tambah"){_,_->val m=ps[sp.selectedItemPosition];val a=amount.text.toString().toLongOrNull()?:0;if(a>0){paymentLines+=PaymentLine(m.code,bank.text.toString().trim(),a);done()}}.setNegativeButton("Batal",null).show()}
 private fun completeSale(method:String,bank:String,lines:List<PaymentLine>){val device=prefs.deviceCode.ifBlank{"ANDROID"};val uuid=UUID.randomUUID().toString();val code="TRX-${SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(Date())}-post${device}";val guide=selectedGuide();val arr=JSONArray();cart.values.forEach{x->arr.put(JSONObject().put("product_id",x.p.id).put("name",x.p.name).put("qty",x.qty).put("price_each",x.p.price).put("discount_amount",x.discountAmount).put("discount_type",x.discountType).put("total",itemNet(x)))};val cashLine=lines.firstOrNull{isCash(it.method)};val payload=JSONObject().put("offline_uuid",uuid).put("transaction_group_uuid",uuid).put("transaction_code",code).put("sold_at",now()).put("user_id",userId()).apply{store.activeShift()?.let{sh->put("shift_offline_uuid",sh.offlineOpenUuid);if(sh.serverId!=null)put("shift_id",sh.serverId) else put("shift_id",JSONObject.NULL)}}.put("branch_id",store.setting("branch_id","1").toLongOrNull()?:1L).put("payment_method",method).put("payment_bank",bank).put("payments",JSONArray().apply{lines.forEach{put(JSONObject().put("method",it.method).put("bank_name",it.bank).put("amount",it.amount).put("cash_received",it.cashReceived).put("cash_change",it.cashChange))}}).put("guide_id",guide?.id?:JSONObject.NULL).put("guide_name",guide?.name?:"").put("customer_name",b.customerName.text.toString().trim()).put("customer_phone",b.customerPhone.text.toString().trim()).put("tx_discount_amount",txDiscAmount).put("tx_discount_type",txDiscType).put("local_device_id",device).put("local_transaction_id",uuid).put("total",total()).put("items",arr);runCatching{store.commitDesktopSale(payload)}.onFailure{toast("Gagal menyimpan: ${it.message}");return};val recItems=cart.values.map{ReceiptItem(it.p.name,it.qty,it.p.price,itemNet(it))};latestReceipt=ReceiptPayload("receipt",code,SimpleDateFormat("dd-MM-yyyy HH:mm:ss",Locale.getDefault()).format(Date()),user().optString("name","Kasir"),store.setting("store_name","Adena"),store.setting("store_subtitle",""),store.setting("store_address",""),store.setting("store_phone",""),store.setting("receipt_footer","Terima kasih"),store.setting("store_logo_url",""),method,total(),cashLine?.cashReceived?:total(),cashLine?.cashChange?:0,58,"","",emptyList(),recItems);cart.clear();txDiscAmount=0.0;b.txDiscountAmount.setText("0");b.customerName.setText("");b.customerPhone.setText("");renderCart();renderProducts();updateStatus();renderReceipt();showPanel(b.panelReceipt);latestReceipt?.let{maybePrint(it)}}
 private fun renderReceipt(){b.receiptContent.removeAllViews();val r=latestReceipt;if(r==null){b.receiptContent.addView(title("Belum ada receipt pada sesi ini"));return};b.receiptContent.addView(title("Receipt ${r.receiptId}"));b.receiptContent.addView(text("Kasir: ${r.cashier}\nMetode: ${r.paymentMethod}\nTotal: ${money(r.total)}"));b.receiptContent.addView(Button(this).apply{text="Print";setOnClickListener{maybePrint(r)}})}
 private fun renderHistory(range:String){val (from,to)=rangeDates(range);val rows=store.history(from,to);b.historyList.removeAllViews();b.historyOmzet.text="Omzet: ${money(rows.filter{it.returnStatus!="returned"}.sumOf{it.total})}";rows.forEach{h->b.historyList.addView(Button(this).apply{text="${h.code}  •  ${h.soldAt}  •  ${money(h.total)}  •  ${h.payment}${if(h.returnStatus=="returned")"  •  RETUR" else if(h.revisionNo>0)"  •  REVISI ${h.revisionNo}" else ""}  •  ${h.syncStatus}";isAllCaps=false;gravity=Gravity.START;setOnClickListener{showHistoryDetail(h)}})}}
 private fun showHistoryDetail(h:PosLocalStore.HistoryTx){val items=store.historyItems(h.groupId);val msg=buildString{append("${h.code}\n${h.soldAt}\n${h.payment} ${h.bank}\nPelanggan: ${h.customer.ifBlank{"-"}}\nGuide: ${h.guide.ifBlank{"-"}}\n\n");items.forEach{append("${it.name} × ${qtyText(it.qty)}  ${money(it.total)}\n")};append("\nTOTAL ${money(h.total)}")};val d=AlertDialog.Builder(this).setTitle("Detail Transaksi").setMessage(msg).setPositiveButton("Tutup",null);if(canModifyHistory()&&h.returnStatus!="returned"){d.setNeutralButton("Edit"){_,_->showEditTransaction(h)};d.setNegativeButton("Retur"){_,_->showReturn(h)}};d.show()}
 private fun showEditTransaction(h:PosLocalStore.HistoryTx){val items=store.historyItems(h.groupId);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(16),dp(16),dp(16))};val qtyInputs=mutableListOf<Pair<PosLocalStore.HistoryItem,EditText>>();items.forEach{x->val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};row.addView(TextView(this).apply{text=x.name;layoutParams=LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1f)});val q=EditText(this).apply{inputType=2;setText(qtyText(x.qty));layoutParams=LinearLayout.LayoutParams(dp(90),ViewGroup.LayoutParams.WRAP_CONTENT)};row.addView(q);box.addView(row);qtyInputs+=x to q};val cat=EditText(this).apply{hint="Kategori alasan revisi"};val reason=EditText(this).apply{hint="Alasan revisi"};box.addView(cat);box.addView(reason);AlertDialog.Builder(this).setTitle("Edit / Revisi ${h.code}").setView(box).setPositiveButton("Simpan Revisi"){_,_->val arr=JSONArray();qtyInputs.forEach{(x,q)->val n=q.text.toString().toDoubleOrNull()?:0.0;if(n>0)arr.put(JSONObject().put("product_id",x.productId).put("name",x.name).put("qty",n).put("price_each",x.price).put("discount_amount",x.discountAmount).put("discount_type",x.discountType))};runCatching{store.reviseLocal(h.groupId,arr,h.payment,h.bank,cat.text.toString(),reason.text.toString(),userId())}.onSuccess{toast("Transaksi direvisi dan stok lokal disesuaikan");renderHistory("today");renderProducts()}.onFailure{toast(it.message?:"Revisi gagal")}}.setNegativeButton("Batal",null).show()}
 private fun showReturn(h:PosLocalStore.HistoryTx){val input=EditText(this).apply{hint="Alasan retur";setPadding(dp(20),dp(10),dp(20),dp(10))};AlertDialog.Builder(this).setTitle("Retur ${h.code}").setView(input).setPositiveButton("Retur"){_,_->runCatching{store.returnLocal(h.groupId,input.text.toString(),userId())}.onSuccess{toast("Retur tersimpan. Stok lokal dikembalikan.");renderHistory("today");renderProducts()}.onFailure{toast(it.message?:"Retur gagal")}}.setNegativeButton("Batal",null).show()}
 private fun renderRecap(){b.recapContent.removeAllViews();b.recapContent.addView(title("Rekapitulasi"));store.recap().forEach{(k,v)->b.recapContent.addView(text("$k\n${money(v)}"))}}
 private fun renderCustomers(){b.customerContent.removeAllViews();b.customerContent.addView(title("Rekap Pelanggan"));store.customerRecap().forEach{x->b.customerContent.addView(text("${x.optString("name")} • ${x.optString("phone")}\n${x.optInt("transactions")} transaksi • ${money(x.optLong("total"))} • terakhir ${x.optString("last")}"))}}
 private fun renderOrders(){b.orderContent.removeAllViews();b.orderContent.addView(title("Order Masuk"));store.orders().forEach{x->b.orderContent.addView(text("${x.optString("order_code")} • ${x.optString("status")}\n${x.optString("customer_name")} • ${money(x.optLong("total"))}\n${x.optString("created_at")}"))}}
 private fun toggleShift(){val sh=store.activeShift();if(sh==null){val input=EditText(this).apply{hint="Kas awal";inputType=2;setText("0")};AlertDialog.Builder(this).setTitle("Buka Shift").setView(input).setPositiveButton("Buka"){_,_->store.openShift(userId(),input.text.toString().toLongOrNull()?:0);updateShift();updateStatus()}.setNegativeButton("Batal",null).show()}else{val input=EditText(this).apply{hint="Kas dihitung";inputType=2};AlertDialog.Builder(this).setTitle("Tutup Shift ${sh.code}").setView(input).setPositiveButton("Tutup"){_,_->store.closeShift(userId(),input.text.toString().toLongOrNull()?:0);updateShift();updateStatus()}.setNegativeButton("Batal",null).show()}}
 private fun updateShift(){val s=store.activeShift();b.shiftStatus.text=if(s==null)"Shift: tidak aktif" else "Shift: ${s.code}";b.btnShift.text=if(s==null)"Buka Shift" else "Tutup Shift"}
 private fun updateStatus(){b.syncCount.text="Pending: ${store.pendingSyncCount()}";b.offlineStatus.text="offline ready"}
 private fun confirmExit(){AlertDialog.Builder(this).setTitle("Keluar POS?").setMessage(if(cart.isEmpty())"Kembali ke Adena Launcher." else "Keranjang saat ini akan dikosongkan dan kembali ke Adena Launcher.").setPositiveButton("Keluar"){_,_->cart.clear();startActivity(Intent(this,AdenaHomeActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP));finish()}.setNegativeButton("Batal",null).show()}
 private fun maybePrint(r:ReceiptPayload){if(pp.getPrinterMac().isNullOrBlank()){toast("Printer belum dipilih");return};if(Build.VERSION.SDK_INT>=31&&ContextCompat.checkSelfPermission(this,Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){latestReceipt=r;btPermission.launch(Manifest.permission.BLUETOOTH_CONNECT);return};printReceipt(r)}
 private fun printReceipt(r:ReceiptPayload){val mac=pp.getPrinterMac()?:return;val bytes=EscPosFormatter.formatReceipt(r,null);lifecycleScope.launch{runCatching{pm.print(mac,bytes)}.onSuccess{toast("Struk tercetak")}.onFailure{toast("Print gagal: ${it.message}")}}}
 private fun rangeDates(range:String):Pair<String,String>{
  val c=Calendar.getInstance()
  fun dayStart(cal:Calendar):String = SimpleDateFormat("yyyy-MM-dd",Locale.US).format(cal.time)+" 00:00:00"
  fun dayEnd(cal:Calendar):String = SimpleDateFormat("yyyy-MM-dd",Locale.US).format(cal.time)+" 23:59:59"
  return when(range){
   "yesterday" -> { c.add(Calendar.DATE,-1); dayStart(c) to dayEnd(c) }
   "7days" -> { val end=dayEnd(c); c.add(Calendar.DATE,-6); dayStart(c) to end }
   "month" -> { val end=dayEnd(c); c.set(Calendar.DAY_OF_MONTH,1); dayStart(c) to end }
   else -> dayStart(c) to dayEnd(c)
  }
 }
 private fun watcher(f:(String)->Unit)=object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,bf:Int,c:Int){f(s?.toString().orEmpty())};override fun afterTextChanged(e:Editable?){}}
 private fun simpleSelected(f:(Int)->Unit)=object:android.widget.AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:android.widget.AdapterView<*>?){};override fun onItemSelected(p:android.widget.AdapterView<*>?,v:View?,pos:Int,id:Long){f(pos)}}
 private fun title(s:String)=TextView(this).apply{text=s;textSize=23f;setTypeface(typeface,Typeface.BOLD);setPadding(4,12,4,12)};private fun text(s:String)=TextView(this).apply{text=s;textSize=16f;setPadding(8,10,8,10);background=round(Color.WHITE)}
 private fun money(v:Long)="Rp "+NumberFormat.getNumberInstance(Locale("in","ID")).format(v);private fun qtyText(v:Double)=if(v==v.toLong().toDouble())v.toLong().toString() else String.format(Locale.US,"%.2f",v);private fun now()=SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(Date());private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show();private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun round(c:Int)=GradientDrawable().apply{setColor(c);cornerRadius=dp(8).toFloat();setStroke(dp(1),Color.rgb(226,232,240))}
}
